version: '3.8'

services:
  app:
    build: .
    container_name: clerky-app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./.wwebjs_auth:/app/.wwebjs_auth
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: clerky-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}

  nginx:
    image: nginx:alpine
    container_name: clerky-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app

volumes:
  mongodb_data: 