version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb+srv://AgenciaVXdb:QLN1YQOvTkKiw7eZ@cluster0.dcgtj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - SESSION_SECRET=whatsvx_secret_2023
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: 